# syntax=docker/dockerfile:1

FROM node:18-alpine
ENV NODE_ENV=production
WORKDIR /ex3
COPY ["package.json","package-lock.json*","./"]
RUN npm install --include=dev
COPY . .
CMD ["node", "src/index.js"]